### ISSUE TITLE
Promotional video(s)

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#102]
I want to make one or two videos to put on the website and github repo explaining what's great about futurecoder and encouraging people to use, contribute, donate, and share. Currently I think there should be two videos. The first should be a short introduction, overview, and sales pitch. The second will demo futurecoder in full and dive into the features and details. I think if I just have one long video then people will be discouraged from watching at all when they see the runtime.

In the first video, these are the main points that I want to show on the screen:

**futurecoder.io is a free platform for beginners to learn programming**

- Interactive and engaging
    - Type and run code at every step
    - Answer multiple choice questions
    - Solve exercises
- Makes learning easy, not frustrating
    - Points out mistakes
    - Gives you tools to find and understand problems
    - Gradually guides you to a solution
    - Teaches Python, a popular and easy language

----

Of course there will be some animation, they will be added bit by bit, and I will have some other visuals. It won't just be talking over some static text. But at least at some point all of that should be visible on the screen. Below is the first draft of the voiceover script:

----

futurecoder.io is a free platform for beginners to learn programming.

Of course there are many ways to learn programming, so let's start with a quick overview of why futurecoder is unique and ideal before we go into more detail.

futurecoder is interactive and engaging, and is carefully designed to make learning easy, not frustrating.

futurecoder makes you learn by doing. You don't just passively read or watch videos. You have to type and run code at every step to advance. As you learn new concepts, you'll be told what code to run, so to make sure you're paying attention you'll need to answer multiple choice questions here and there. Then you'll complete exercises to practice, reinforce your knowledge, and improve your problem solving skills.

Programming can be tricky, and sometimes has people pulling their hair out in frustration, especially beginners. That's really terrible for learning and motivation. futurecoder does everything it can to keep the learning experience smooth and painless, while still avoiding handing you the answers on a silver platter.

It looks for mistakes in your code and explains them to you so you can fix them. This includes looking for generic mistakes at all times as well as specific checks tailored to each exercise. It also provides several tools to help you find and understand problems, including three different debuggers conveniently built in that let you visualise code in different ways.

If none of this helps, you can ask for small hints which gradually guide you to the solution. And if these aren't enough, the solution can be slowly revealed bit by bit until you have just enough information to fill in the remaining gaps for yourself. Sometimes the solution may even be given to you but shuffled out of order so that you have the task of putting it in the right order.

futurecoder teaches you Python, which is generally considered one of the easiest languages to learn. Python has a simple friendly syntax that's almost like English, letting you focus on the actual logic that matters instead of the details of the syntax. If you look at lists of the most popular programming languages, you'll find that most of them have Python in the top 2, sometimes even at number 1. It can be used for many different things and is used a lot by big companies including Google, Instagram, Reddit, and Spotify. Even if learning Python isn't your main goal, it's a great place to start. Once you can program in one language, learning other languages is much easier. And if you already know a little Python, you can jump into any part of the course. You don't have to start again from scratch.

Again, all of this is completely free. There's no ads, no free trials, no locked paid content. Everything is open source.

There's just two caveats. Firstly, the site is free, but it still costs money to host it. So just as you might donate to Wikipedia so that they can continue to provide free knowledge, we ask that you please consider donating to futurecoder to keep it running. Without funding, the site can only run on minimal infrastructure and can't handle many users, so we can't guarantee that it will be stable for you.

Secondly, futurecoder is still under development. You can start now and learn a lot, but there is plenty of work to be done on our side, including writing more course material. If you're an educator or a software developer, we'd love your help building futurecoder. Come join us on GitHub or Slack.

If you can't contribute code or money, you can help us by spreading the word. Give this video a like, leave a star on GitHub, and share this video or the website on your social media. This makes a huge difference and will be greatly appreciated. If you want to be informed when futurecoder is ready for a full release, leave your email address on the website and we'll let you know.

If you want to dive deeper and learn more about futurecoder, click here to watch the next video where we do a full demonstration of futurecoder and all its features as well as discuss the decisions behind the design.

----

Any thoughts? The details will probably evolve a lot, but is the general structure OK?

**Comment by acivitillo** [comment]
I would start with one question: who are those promotional videos for?

If you target python beginners, then in my opinion your content ideas are going in the right direction. If you are targeting content creators who need futurecoder to create their own courses, you might need to focus on that more.

Are you trying to sell futurecoder the site/service or futurecoder the self hosted custom content django app?

**Comment by alexmojaki** [comment]
You are the only person I know who's interested in writing their own course. It's not my target audience. I'm focused on just the main site with its one course.

The end goal right now is to get contributors. The video is partly supposed to impress potential contributors directly, as well as hype up actual learners and other viewers so that they share futurecoder and more potential contributors are reached. At least at the moment futurecoder isn't actually ready for lots of learners.
