### ISSUE TITLE
Improve home page even futher

### ISSUE THREAD

**Issue by ChrisjanWust** [alexmojaki/futurecoder#104]
- [ ] Show something of what the project looks like under the hood. Specifically, so GIFs of project features would be excellent. Idea comes after showing the page to a friend and he immediately wanted to know how the actual project looked, but didn't want to go through logging in etc.
- [ ] Flesh out footer

Not of immediate priority.

**Comment by alexmojaki** [comment]
I think we need a gallery like https://getbootstrap.com/docs/4.0/components/carousel/#with-captions with the pictures currently in the README, and later there will be videos that demonstrate it in motion.
