### ISSUE TITLE
Unhandled Rejection (SecurityError) the operation is insecure (in Firefox)

### ISSUE THREAD

**Issue by spamegg1** [alexmojaki/futurecoder#130]
While developing on Firefox with `poetry` and `npm` I run into the following error every time I navigate to a page:

![linux_firefox_poetry_npm_dev](https://user-images.githubusercontent.com/4255997/107142510-a1e69a00-6940-11eb-856c-e4dca70903ee.png)

It only happens in Firefox. It is not debilitating, I can continue using the development site `localhost:3000` by clicking "X" but it is quite annoying while developing. I guess I'm the only loser in the world who still uses Firefox.

The issue is `navigator.serviceWorker.ready.then(...)` in `frontend/src/serviceWorker.js`. Specifically the `ready` part.

I also found the same issue while running the production site `futurecoder.io` on Windows with Firefox. It does not show the error page like above, but the console shows the same error `Uncaught (in promise) DOMException...` coming from the same line of code (except it's in the optimized production code `main.xxxxxxxx.chunk.js:1`).

I experimented with a few different workarounds:

- adding a `catch` clause to the `unregister` function:

  ```javascript
  export function unregister() {
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.ready.then(registration => {
        registration.unregister();
      }) // I added the line below
      .catch(err => console.log("Service worker failed to unregister"));
    }
  }
  ```

- changing `serviceWorker.unregister()` to `serviceWorker.register()` at the end of `frontend/src/index.js`

- commenting out `serviceWorker.unregister()` altogether

- deleting `serviceWorker.js` (and removing references to it in `index.js`)

### Service workers

I ended up learning about service workers. First of all they are OPTIONAL. From the top of `serviceWorker.js`:

```javascript
// This optional code is used to register a service worker.
// register() is not called by default.

// This lets the app load faster on subsequent visits in production, and gives
// it offline capabilities. However, it also means that developers (and users)
// will only see deployed updates on subsequent visits to a page, after all the
// existing tabs open on the page have been closed, since previously cached
// resources are updated in the background.

// To learn more about the benefits of this model and instructions on how to
// opt-in, read https://bit.ly/CRA-PWA
```

So unless `unregister()` is switched to `register()` the file is doing nothing, just sitting there. I confirmed this by looking at the "Applications" tab in the Developer Console. The "Service Workers" section shows nothing, so clearly `futurecoder.io` is not using them.

***What do service workers do exactly?***

Best source on the subject is CRA itself: https://create-react-app.dev/docs/making-a-progressive-web-app/

They are for "offline-first" progressive web applications. Mostly beneficial for simple mobile apps. It's a technology that is trying to replace the previous `AppCache` technology that had a lot of problems. Service workers can cache files offline so the page can load faster upon subsequent visits, or run entirely offline (if possible). They first need to be "registered" to run.

Modern browsers are acutely aware of their existence, as there is a dedicated "Service workers" section under the Applications tab of all developer consoles. Strangely, unregistering service workers is the default behavior in Chrome-based browsers. There is a check-box in the Applications/Storage tab.

So I tried `serviceWorker.register()` first. I thought "even if we don't use it, just register it so the problem goes away." But that requires a second `service-worker.js` file to give the worker some desired behavior. Otherwise the browser gives a `service-worker.js 404 Not Found` error. Exchanging one error for another. (Here is a sample generic [such file](https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/basic/service-worker.js))

Moreover offline caching would probably be bad for `futurecoder`. Our content changes frequently, so users might end up seeing older content, or it can lead to conflicts and confusion. CRA acknowledges as such:

```
Users aren't always familiar with offline-first web apps.
```

I'm guessing `futurecoder` would straight up not work offline because it needs the database and the backend for running user code.

It can also create issues (like this one) in development. CRA acknowledges as such:

```
The service worker is only enabled in the production environment, e.g. the output of npm run build. It's recommended that you do not enable an offline-first service worker in a development environment, as it can lead to frustration when previously cached assets are used and do not include the latest changes you've made locally.
```

Then I remembered something: while taking [Fullstack Open](https://fullstackopen.com/en) we would ALWAYS delete the `serviceWorker.js` file (or `serviceWorker.ts` for TypeScript) because we never use it.

### Proposal

***My proposal: deleting `serviceWorker.js`.*** This is OK because the file is a generic, default part of `create-react-app` so even if we decided to use it in the future, we can simply put the file back in. Moreover deleting this file is quite common, most sites do not use service workers at all. I tested it and it works just fine. I can make a PR to check the deployment.

*A less intrusive, less permanent solution is: adding the `catch` clause.* This gets rid of the error page shown in `localhost:3000` and the error in the Developer Console (which now just says "Service worker failed to unregister"). I'm guessing it would get rid of the error for the production site too, once deployed. Note that if we decide to use service workers in the future we'll have to remove this clause.

*Another solution would be: "hey spamegg stop using Firefox you loser!"* There seems to be a very strong bias towards Chrome and against Firefox in the web dev world. Even Fullstack Open says "do not use Firefox, use Chrome, that's what we use to teach." 

I refuse to use Google products, sorry. I can just remove the file whenever I'm developing, or I can stick to `docker-compose` (which does not give the error). But obviously *some* users will use Firefox, and in the future there might be other contributors who use Firefox.

(Below are my findings on trying different things on various browsers and operating systems, just in case you're curious. They are not too important.)

<details>
    <summary>details on various browsers and operating systems</summary>
Unhandled Rejection (SecurityError) the operation is insecure.
a.k.a. Uncaught (in promise) DOMException the operation is insecure.

Ignoring other unrelated errors and warnings:

Production site futurecoder.io:

- Linux:
  - Firefox (85.0 for Linux Mint): OK
    Application/Service workers shows "No service workers found"
  - Opera (Version:74.0.3911.75): OK
    Application/Service workers shows nothing
- Windows:
  - Firefox (85.0): does NOT show error page (only shown in development), but...
    Uncaught (in promise) DOMException: the operation is insecure. in main.xxxxxxxx.chunk.js:1
    this extremely long optimized line of code contains at the very end:
    `navigator.serviceWorker.ready.then((function(e){e.unregister()}))`
    Application/Service workers shows "No service workers found"
  - Opera (74.0.3911.75): OK
    Application/Service workers shows nothing
  - Edge: same as Opera

development site (localhost:3000) is:

- Linux:
  - with docker-compose:
    - Firefox (85.0 for Linux Mint): does NOT show the error page "Unhandled Rejection". But...
      Uncaught (in promise) DOMException: the operation is insecure. in main.xxxxxxxx.chunk.js:1
      this extremely long optimized line of code contains at the very end:
      `navigator.serviceWorker.ready.then((function(e){e.unregister()}))`
      Application/Service workers shows "No service workers found"
    - Opera (Version:74.0.3911.75): OK
      Application/Service Workers shows nothing
      The console has an "Unregister service workers" option under the
      Application/Storage tab which is checked by default.
      Unchecking and reloading, still OK.
  - with poetry/npm:
    - Firefox: Shows the error page "Unhandled Rejection (SecurityError): The operation is insecure.
      Clicking on X goes back to site, works fine.
      Moving to any other page from TOC, same issue again.
      Uncaught (in promise) DOMException: the operation is insecure. in serviceWorker.js:131
      Application/Service workers shows "No service workers found"
    - Opera: OK
      Application/Service Workers shows nothing
- Windows:
  - with poetry/npm:
    - Firefox: same as Linux/Firefox/poetry-npm
    - Opera: same as Linux/Opera/poetry-npm
    - Edge: same as Opera

if I add the `catch(err => console.log("Service worker failed to unregister"))`
to serviceWorker.js and rebuild, development site (localhost:3000) is:

- Linux:
  - with docker-compose:
    - Firefox (85.0 for Linux Mint): OK
      console says: Service worker failed to unregister
      Application/Service workers shows "No service workers found"
    - Opera (Version:74.0.3911.75): OK
      Console says nothing
      Application/Service workers shows nothing
  - with poetry/npm:
    - Firefox: OK
      console says: Service worker failed to unregister
      Application/Service workers shows "No service workers found"
    - Opera: OK
      console says nothing
      Application/Service workers shows nothing
- Windows:
  - with poetry/npm:
    - Firefox: same as Linux/Firefox/poetry-npm
    - Opera: same as Linux/Firefox/poetry-npm
    - Edge: same as Opera

Instead, if I change to: `serviceworker.register()`; in `index.js` and rebuild, development site (localhost) is:

- Linux:
  - with docker-compose:
    - Firefox (85.0 for Linux Mint): does NOT show the error page. But...
      Uncaught (in promise) DOMException: the operation is insecure. in main.xxxxxxxx.chunk.js:1
      this extremely long optimized line of code contains at the very end:
      `navigator.serviceWorker.ready.then((function(e){e.unregister()}))`
      GET http://localhost:3000/service-worker.js 404 Not Found
      Application/Service workers shows "No service workers found"
    - Opera (Version:74.0.3911.75): OK
      GET http://localhost:3000/service-worker.js 404 Not Found
      Application/Service workers shows nothing
  - with poetry/npm:
    - Firefox: OK
      Application/Service workers shows "No service workers found"
    - Opera: OK
      Application/Service workers shows nothing
- Windows:
  - with poetry/npm:
    - Firefox: same as Linux/Firefox/poetry-npm
    - Opera: same as Linux/Firefox/poetry-npm
    - Edge: same as Opera

Instead, if I altogether comment out `serviceworker.unregister()`; in `index.js`
and rebuild, development site (localhost) is:

- Linux:
  - with docker-compose:
    - Firefox (85.0 for Linux Mint): OK
      Application/Service workers shows "No service workers found"
    - Opera (Version:74.0.3911.75): OK
      Application/Service workers shows nothing
  - with poetry/npm:
    - Firefox: OK
      yellow warning: "serviceWorker" defined but never used
      Application/Service workers shows "No service workers found"
    - Opera: OK
      yellow warning: "serviceWorker" defined but never used
      Application/Service workers shows nothing
- Windows:
  - with poetry/npm:
  - Firefox: same as Linux/Firefox/poetry-npm
  - Opera: same as Linux/Firefox/poetry-npm
  - Edge: same as Opera
</details>

**Comment by alexmojaki** [comment]
Wow, this is quite the investigation! Thank you!

It looks like we can go ahead and remove this, you can merge your PR and close this issue if you want. There's still some questions I'm curious about, but only if you can answer them with minimal effort. They're not important.

1. `Unhandled Rejection (SecurityError) the operation is insecure` and `Uncaught (in promise) DOMException the operation is insecure` *sound* like different things. In particular `DOMException` sounds like it has to do with the DOM which sounds unrelated to unregistering service workers. As far as you can tell, they're coming from the same thing? Any idea why the message changes?
2. What is the point of `unregister()` by default? If CRA wants to encourage considering opting in to service workers, why not start with a commented out `register()` line? Surely there's no point in unregistering when you've never registered before?
3. docker-compose and production behave identically, right? They both use the same Dockerfile and a built JS package, so I expect them to. The differences are in the backend.

> Another solution would be: "hey spamegg stop using Firefox you loser!" There seems to be a very strong bias towards Chrome and against Firefox in the web dev world. Even Fullstack Open says "do not use Firefox, use Chrome, that's what we use to teach."

> I refuse to use Google products, sorry. I can just remove the file whenever I'm developing, or I can stick to docker-compose (which does not give the error). But obviously some users will use Firefox, and in the future there might be other contributors who use Firefox.

Haha no, you're not a loser. I'm glad you use Firefox, it's valuable to have you testing the behaviour in Firefox because as you say some users use Firefox and we can't stop that. I imagine a course like FSO wants all students to use Chrome so they can give a single uniform set of instructions to click X > Y > Z in developer tools. That doesn't mean they require you to use Chrome for life or only cater to Chrome users. 

futurecoder would not work offline, no. User code always runs in the server. Caching to improve performance over a slow connection, particularly the initial load, is probably very doable, but I'm not interested in that kind of optimisation now.

**Comment by spamegg1** [comment]
1. They ARE the same thing. In development the error explicitly comes from `serviceWorker.js:131` whereas in production it gets optimized into `main.xxxxxxxx.chunk.js:1` but in the Debugger section I can see that it is the same code that is causing the issue. I'm not sure why the name changes. I believe the error PAGE is shown by React only in development so they have their own names for things, whereas the browser is not super smart to figure it out from a bunch of optimized mess of a code. `DOMException` is probably a generic name for a lot of things.
2. I agree, this is very weird. I also thought starting with a commented out `register()` would make more sense. Chrome-based browsers have "Unregister service workers" option that is checked by default. Not sure, maybe registering is considered "tracking behavior" or something?
3. Yes, `docker-compose` and production work the same.
