### ISSUE TITLE
Upgrade to Python 3.9

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#140]
While I don't know of any huge difference it would make, I don't want futurecoder to fall far behind the latest Python version. This requires ensuring that the dependencies are ready. In particular I know this requires some work in my own dependencies:

- https://github.com/alexmojaki/cheap_repr
- https://github.com/alexmojaki/birdseye
- https://github.com/alexmojaki/snoop

At the very least these need to be officially testing 3.9 in travis or github actions. They might also need fixes. I don't expect problems for cheap_repr. birdseye and snoop need to add golden files for 3.9 and likely need fixes due to changes in the AST, especially birdseye.

Following this:

- Check if the Python build installed in the Dockerfile is reasonably fast, see https://pythonspeed.com/articles/faster-python/
- Look at upgrading Django

**Comment by spamegg1** [comment]
`cheap_repr` is done here: https://github.com/alexmojaki/cheap_repr/commit/ba9d0ccf0da42706977aabeafab86f9b5d589076

Next up are `birdseye` and `snoop`.

**Comment by spamegg1** [comment]
`birdseye` is done here: https://github.com/alexmojaki/birdseye/commit/2b32b48b555d31226a1ed495ed260a1d43afc7e1
Only `snoop` is left.

**Comment by spamegg1** [comment]
`snoop` is done here: https://github.com/alexmojaki/snoop/commit/bfae6e976725665489a988976a027a27416bb463

I'm not sure about the next steps. Maybe someone else can look into it?

**Comment by alexmojaki** [comment]
The last bullet points are just some future thoughts for after we upgrade to Python 3.9. They are not the next steps.

Please also test 3.9 in https://github.com/alexmojaki/dryenv

**Comment by alexmojaki** [comment]
And https://github.com/gristlabs/asttokens

**Comment by alexmojaki** [comment]
Relevant: https://github.com/gristlabs/asttokens/issues/65 and https://github.com/gristlabs/asttokens/issues/59

**Comment by spamegg1** [comment]
`dryenv` should be good to go: https://github.com/alexmojaki/dryenv/pull/1

**Comment by spamegg1** [comment]
`asttokens` is addressed here https://github.com/gristlabs/asttokens/pull/66
Now that #142 is merged, closing this...
