### ISSUE TITLE
Friendly-traceback changed its name

### ISSUE THREAD

**Issue by aroberge** [alexmojaki/futurecoder#146]
Hi,

If you want to use the latest version, please be advised that friendly-traceback is know simply known as friendly.  All references to `friendly_traceback` can be replaced by `friendly`.

**Comment by alexmojaki** [comment]
Thanks. Why the change? Seemed like a good name.

Also what happened to versions 0.2.42 to 0.2.89?

**Comment by aroberge** [comment]
I sort of explain the reason for the name change here: https://aroberge.blogspot.com/2021/03/friendly-traceback-will-have-new-name.html

With many new changes to the console api (`www()`, `history()`, `back()`, etc.), better support for IDLE, etc., I was planning to jump from 0.2.xx to 0.3.0.   I decided to change the name prior to changing version to 0.3, and wanted to give me some "breathing room" for uploading to Pypi and testing installation. Nothing really rational about the choice.
