### ISSUE TITLE
setup failed on fish shell

### ISSUE THREAD

**Issue by pwwang** [alexmojaki/futurecoder#151]
`poetry` not found is reported. 

But when I try to do `which poetry` after the failure, it was found at the right place (`~/.poetry/bin/poetry`)
I've also checked `fish_user_paths`, which has been successfully modified.

```
~/github/futurecoder/backend master
❯ ./setup.sh                                                             (py39) 
+ poetry --version
./setup.sh: line 5: poetry: command not found
+ curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
+ python
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the `fish_user_paths` universal variable.

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.1.5
  - Downloading poetry-1.1.5-linux.tar.gz (72.34MB)

Poetry (1.1.5) is installed now. Great!

Poetry's bin directory ($HOME/.poetry/bin) has been added to your `PATH`
environment variable by modifying the `fish_user_paths` universal variable.

+ poetry install
./setup.sh: line 7: poetry: command not found
```

Rerun `setup.sh` worked as expected.

PS: Might need a little hint in the docs on setup in conda. One of the dependencies (`rcssmin`) needs `x86_64-conda_cos6-linux-gnu-gcc` to be alive in the environment, which can be installed by `conda install gxx_linux-64`.

**Comment by alexmojaki** [comment]
This is fine, installing poetry in setup.sh is already a convenience. Having to preinstall some things (python, bash, curl, npm...) is normal.

Similarly I'm hesitant about giving instructions for things like conda and bloating the README. We're already trying to support Windows, `conda install gxx_linux-64` is not going to work there. Was it hard for you to find that solution?

**Comment by pwwang** [comment]
No, not so much googling.

Maybe direct users to rerun the script on 
```
./setup.sh: line 7: poetry: command not found
```
?

**Comment by alexmojaki** [comment]
No, I think it's fine.
