### ISSUE TITLE
Markdown not rendered properly in message card

### ISSUE THREAD

**Issue by pwwang** [alexmojaki/futurecoder#158]
Step to reproduce:

- Go to TOC, then "Writing Programs"
- Type "a=1" in the editor
- Hit "Run"

![image](https://user-images.githubusercontent.com/1188067/117050948-d57c5a80-acca-11eb-94c1-b53080ac384e.png)

The markdown marks are supported to be rendered.

**Comment by alexmojaki** [comment]
Thanks. This is just in the pyodide branch, right?

**Comment by pwwang** [comment]
Yep, just found it in that PR (#157).

**Comment by alexmojaki** [comment]
Seems fixed now
