### ISSUE TITLE
Allow using from China

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#163]
Original report from Slack:

> hello, I am from China, I am very happy to find this platform, and I want to use it in my course, but my students do not connect the google, I want to know there are some others ways for us to use this platform. think you!

Firebase is blocked in China, need to find a workaround.

**Comment by alexmojaki** [comment]
Looks like several potential users are running into this and it's becoming more important, especially since someone has started translating futurecoder to Chinese.

For starters, there should at least be an error message when the site fails to connect to firebase. Right now it just gets stuck on loading.

Options to actually make the site work:

1. Set up a server to proxy requests to firebase.
2. Use local storage as a fallback, which might also help in case of other connection problems, but wouldn't allow logging into the account on another computer.
3. Find an alternative to firebase with the same features and reimplement all that code. Auth is the biggest concern here.

**Comment by hangtwenty** [comment]
I think that https://supabase.com might be worth considering. (I've heard good things, anyways!)

**Comment by alexmojaki** [comment]
That's what I thought, but when I looked more deeply it actually seemed very difficult. I'd be thrilled if someone could manage, because it seems like in the long term I'm going to have to leave firebase over this.

**Comment by hangtwenty** [comment]
I've heard that Supabase can be a good alternative to Firebase, so I'm curious if Supabase would be accessible to the users who are currently unable to access Firebase. I haven't tried that migration myself [but I found this](https://github.com/supabase-community/firebase-to-supabase)

**Comment by alexmojaki** [comment]
Interesting! I'm not in a hurry to migrate, but it'd be nice if this was production ready: https://github.com/supabase/ui

**Comment by berhalak** [comment]
Hi Alex.

Some insights that might help. I have two accounts one works and one doesn't. For the one that doesn't the error is here:

![image](https://user-images.githubusercontent.com/11277225/157984359-df654770-cfb2-4821-ab56-54ec017b8053.png)

For the account that doesn't work currentUser.uid is my email, not uid. When I'm using the second account, this uid is some valid alphanumeric value.

**Comment by alexmojaki** [comment]
Thanks for looking into this @berhalak. Looks like I messed up the migration of users from django to firebase. Probably not worth fixing now.
