### ISSUE TITLE
Fundraising

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#20]
Eventually we will need to launch this project with some serious hosting to handle large numbers of users. We will need donations to sustain the project.

This isn't a pressing issue yet, as there's still lots of work to do before the project is ready for users, but it's something worth thinking about. I've never done this before so I'd love to hear ideas.

**Comment by cdnsteve** [comment]
Some potential ideas: 

- Github Sponsors, sponsors could potentially unlock premium content
- Kickstarter
- Indiegogo

**Comment by alexmojaki** [comment]
I'd like all content to always be unlocked, but maybe that idealism won't last.

**Comment by alexmojaki** [comment]
Solved by #157 

Donations can still be made via opencollective, as running this project isn't free, but we shouldn't need "serious hosting" so for the foreseeable future money shouldn't be a big issue.
