### ISSUE TITLE
Include metadata for site

### ISSUE THREAD

**Issue by harimm** [alexmojaki/futurecoder#204]
I think we can include the open graph metadata tags https://ogp.me/ so that when we share or embed a link, a better description would be shared.

Currently the preview is very basic
<img width="1004" alt="Screenshot 2021-11-01 at 9 51 47 PM" src="https://user-images.githubusercontent.com/2451152/139710409-6622a43d-55aa-45a3-840e-c336ae9c51ce.png">

If an image as well as description is included, it would be more appealing

**Comment by alexmojaki** [comment]
This is a good idea! Do you have anything in mind for an image? Do you want to try doing this?

**Comment by harimm** [comment]
I think we can put the futurecoder icon itself. I would like to take a crack at this
