### ISSUE TITLE
Show message when submission only differs by spaces

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#237]
Similar to the generic case sensitivity check, add a generic check that shows a message when the submission doesn't pass but the submitted and correct program strings are equal after removing all spaces. Example where this would have helped: https://www.reddit.com/r/InternetIsBeautiful/comments/qo0j20/i_built_futurecoder_a_100_free_and_interactive/hml4ihw/

**Comment by spamegg1** [comment]
This isn't good enough, is it? Can't be that easy :smile:
```python
# core/text.py
...
class VerbatimStep(Step):
    program_in_text = True

    def check(self):
        ...

        if self.truncated_trees_match(
                ast.parse("".join(self.input.split())),
                ast.parse("".join(self.program.split())),
        ):
            return dict(
                message="That's almost correct! You might be missing a space somewhere "
                        "in your answer. `Hello` is different than `Hello ` (note the space!). "
                        "Adding strings with `+` does not add a space between the two strings. "
                        "You'll have to add spaces yourself where needed!"
            )
``` 
![ex](https://user-images.githubusercontent.com/4255997/146594950-2f4323c3-c5b0-44c8-bf41-62886f52cdee.png)
What else is needed? (I forgot how to do futurecoder stuff :smile: ) At least it's a starting point for a new contributor maybe?

**Comment by alexmojaki** [comment]
So good to see you again @spamegg1! I've missed you, wanted to celebrate all the good news with you!

That's the right idea, yes.

**Comment by alexmojaki** [comment]
Actually it's a bit more complicated, because that will break for code with multiple lines. In particular it'd be great to catch cases where the indentation is the only problem.

**Comment by alexmojaki** [comment]
I think it'd be best to only check the string nodes and return a message specifically about strings like you had above. That's what the original user report was about, and that seems like enough to close this issue. Dealing with indentation would be nice, but it's just an idea, I have no evidence it would help in practice.

If we ever look at dealing with indentation, the AST doesn't give anything easy as you've discovered. A starting point could be just comparing the strings without spaces and hoping there's no other differences like the type of quotes.
