### ISSUE TITLE
quit(), exit() and the other exit commands freezes progress in the lesson

### ISSUE THREAD

**Issue by martinvilu** [alexmojaki/futurecoder#267]
Using the `quit()` function does what it should, but locks out progress without further messages.

All exit options work in the same way; `sys.exit`, `quit()`, `exit()` and `raise SystemExit`

Reloading the page solves the lockup.

![2022-01-06_17-13_2](https://user-images.githubusercontent.com/56625/148445401-25e14b43-327a-4a6a-bce1-014ab0f6b662.png)

It's not on the regular learning path, but if a student copies and pastes something from the web they might encounter this problem.

**Comment by alexmojaki** [comment]
This is fixed now
