### ISSUE TITLE
Process dies trying to run Python command on Docker

### ISSUE THREAD

**Issue by opheron** [alexmojaki/futurecoder#28]
While runnning locally on Docker, when trying to run 1+2 on "Introducing The Shell", the in-browser command prompt returned:

`The process died.
Your code probably took too long.
Maybe you have an infinite loop?
`

This was on first install. Now, on second run, I can't seem to reproduce the problem.

**Comment by alexmojaki** [comment]
Thanks for the report, I appreciate the effort. But since you can't reproduce it and neither can I, I think it makes sense to close this for now. Please reopen if you find more information.

**Comment by alexmojaki** [comment]
@opheron I have implemented open chapters/pages as we discussed in #38. Please see the description and try out the test environment.
