### ISSUE TITLE
[enhancement] Suggestions for UI design and TOC

### ISSUE THREAD

**Issue by BobAnkh** [alexmojaki/futurecoder#31]
I'm new to this project so please forgive me if I get something wrong. 

Here is just my suggestions for the UI design and TOC after experiencing several chapters.

1. Is it possible to place the shell on the right or upper right in the first few chapters? Placing the shell in the lower right part with the upper right part all blank is a little bit uncoordinated to me.
2. Is it possible to place the TOC(table of content) first and let users to choose the part to learn ? I think different users may have different foundations and knowledge for python. And they can directly jump to the part they are more concerned about and bypass the basic parts they have already mastered that will surely cost them some time

Besides, is it more convinient for users to learn with it if we have translations?

Thank you for considering my suggestions.

**Comment by alexmojaki** [comment]
Thanks for the feedback!

1. Someone else has mentioned this before, so I think it's worth doing. The shell can fill the right half of the screen until the editor appears. I invite you or anyone else to make a PR making this change.
2. This has also come up in discussions, and you're right, it should be easy to jump to any section. I will make a new issue soon detailing my thoughts on this.
3. Translations are not a priority at the moment. We don't even have one complete course, and until it's finished it's probably going to change.

**Comment by BobAnkh** [comment]
Thank you for your reply!

I'm familiar with python but not with javascript. So maybe I can't help with this frontend issue. I will keep an eye on the project to see if there is something that I can help. I'm interested in this project.

If there is something that I can help with, please tell me.

**Comment by alexmojaki** [comment]
The easiest thing anyone can help with is to brainstorm course content in #23.

**Comment by spamegg1** [comment]
For the Table of Contents: it would be nice to have a topic tracker either at the top or bottom, displaying the name of the current topic, with buttons to other topics (similar to edX or Coursera).

**Comment by alexmojaki** [comment]
@spamegg1 can you describe your idea in more detail?

**Comment by alexmojaki** [comment]
@BobAnkh @spamegg1 I have implemented point 2 in #38. Please see the description and try out the test environment.

**Comment by BobAnkh** [comment]
@alexmojaki When I try the page `Functions And Methods For Lists` in ch06, I suddenly got some ideas. But I'm not sure if this is what we really need, so I would like to discuss here first.

Can we add a button or provide a way to clear shell or reset shell? I mean, a beginner may try several times before they find the correct way and they would likely to use shell to test their method (at least I prefer to explore new things in shell rather than directly write the program). Also their answer is judged by shell output so maybe they prefer to explore it if it is not a big project. Whenever I explore a new method but get the wrong result, I have to reset the variables. Besides, can we set the variable we suppose to use so that students may focus on the method itself?

I will explain the ideas more clearly with this example:

![image](https://user-images.githubusercontent.com/44333669/89700325-da8cc300-d95f-11ea-8230-9a21c921633d.png)

This is the section you provide at the page `Functions And Methods For Lists` in ch06. (Could you please tell me how can I replay the section?)

When I want to solve it, I have to copy the line `nums = [1, 2, 3, 4, 5]` to the shell first and then try to solve it. And if I try a wrong way, e.g. get `[1, 2, 3, 4, 5, 9]`, I have to paste the line again to reset the variable. So my ideas are that: we provide a way or a button to reset the shell with variable `nums` reset to `[1, 2, 3, 4, 5]` and delete other variables for this section.

I'm just sharing my thinking so please forgive me if it is of no need.

**Comment by alexmojaki** [comment]
You can replay the section by going to that page in the TOC and then turning on Developer mode (see the README) and reversing steps.

In this particular exercise, the user is just required to enter `<something>.insert(2, 9)`. They don't have to use the variable `nums` or the value `[1, 2, 3, 4, 5]`. We could maybe tell them that, it just felt like clutter to me.

I think the problem here is asking them to use the shell. It makes more sense in the previous exercise when we want them to enter `max([21, 55, 4, 91, 62, 49])` which has a value. They can do everything in one small line and see the result. In this case I think we should ask them to enter this program in the editor:

```python
nums = [1, 2, 3, 4, 5]
<do something to nums>
print(nums)
```

and then fill in the middle line so that it prints `[1, 2, 9, 3, 4, 5]`. What do you think?

**Comment by alexmojaki** [comment]
> I'm just sharing my thinking so please forgive me if it is of no need.

Please always share your thoughts, don't be shy.

**Comment by BobAnkh** [comment]
> You can replay the section by going to that page in the TOC and then turning on Developer mode (see the README) and reversing steps.

I mean for normal users to replay the section(e.g. as a user, I would like try other methods to see if it gives me the right answer to the question)

And as for the idea of reset, I just think that idea may be beneficial to the whole project, if there may be a more complex situation of future courses(e.g. cumtom courses). To be honest, it is not necessary for courses at this moment to have reset.

> What do you think?

As for this section, I agree with your idea. We should make it more clear for the students what they should do with the provided condition. This is the core concept of my suggestion to provide pre-set variables. I think your solution is more simple and clear. Just tell them to paste the program on the editor and fill the line. This makes it more clear of what I should do to the question.

**Comment by alexmojaki** [comment]
> I mean for normal users to replay the section(e.g. as a user, I would like to try other methods to see if it gives me the right answer to the question)

You can always run any code at any point in the course. The only downsides of trying to resolve an old exercise in the wrong place are:

- You have to check for yourself if you got the answer right. In most cases I would say this isn't very hard, certainly not in this example.
- You might get some messages from the system assuming that you're solving the current exercise and doing something wrong. But these will only appear once and you can ignore them.

Do you think this is a major problem? I don't want to complicate the interface with buttons that aren't really needed.

> And as for the idea of reset, I just think that idea may be beneficial to the whole project

But it's not clear to me what it would do in most cases. In particular most steps revolve around the editor, not the shell.

> As for this section, I agree with your idea.

Great, I'm glad this was brought up. Want to make a PR?

**Comment by BobAnkh** [comment]
> Do you think this is a major problem? I don't want to complicate the interface with buttons that aren't really needed.

Because I myself prefer to be judged by the system not myself, so I propose this. It is not a big problem to judge by myself in current cases. So I think we can consider this feature if someone propose it again.

> But it's not clear to me what it would do in most cases. In particular most steps revolve around the editor, not the shell.

I just mention the idea of reset as an note in case of future need. But it seems not useful at this time.

> Great, I'm glad you brought this up. Want to make a PR?

Do I only need to change the relevant instruction? If so, I would like to make a pr. If codes should be changed, could you please specify the relevant content I should consider?

**Comment by alexmojaki** [comment]
In this case it was easier to just do it myself in #40, take a look.

**Comment by BobAnkh** [comment]
I think this issue can be closed because the suggestions have been either implemented or moved to a individual issue.
