### ISSUE TITLE
Cursor in wrong place in shell

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#33]
The cursor should appear directly after `>>>` in the shell, like this:

![Screen Shot 2020-07-30 at 19 50 47](https://user-images.githubusercontent.com/3627481/88956733-122fa700-d29e-11ea-8f48-d5b34ee375a0.png)

On my machine this works correctly in Chrome, but not in Firefox or Safari, where it does this:

```
>>>
123 (what I type goes here, not the line above)
```

After I hit Enter it becomes:

```
>>> 123 (what I typed earlier)
(result appears here)
```

Thanks @spamegg1 for reporting this in #27, I didn't know about it because I only use Chrome.

The place to start looking for the problem is in `frontend/src/shell/Terminal.jsx`. The code is copied and modified from the project `react-console-emulator`, it might be helpful to look at what happens there and if what has changed since the code was copied.

**Comment by spamegg1** [comment]
OK, so you were able to reproduce this, right? Then it's not just me.

**Comment by alexmojaki** [comment]
Yes, it's not just you. It's probably lots of people.
