### ISSUE TITLE
Using pyscript?

### ISSUE THREAD

**Issue by pwwang** [alexmojaki/futurecoder#344]
Would it be easier to implement using [pyscript](https://anaconda.cloud/pyscript-python-in-the-browser)?

**Comment by alexmojaki** [comment]
Currently on https://pyscript.net/ it says:

> Please be advised that PyScript is very alpha and under heavy development. There are many known issues, from usability to loading times, and you should expect things to change often. We encourage people to play and explore with PyScript, but at this time we do not recommend using it for production.

So at the very least it would need to be a bit more stable. Besides that, it's not clear to me that pyscript currently fits futurecoder's use case.

Amusing side note: in a conversation with someone else about `executing` and `varname`, they thought you were Peter Wang.

**Comment by alexmojaki** [comment]
They said they were friends with Peter Wang, he clearly *is* a big deal (e.g. CEO of Anaconda) and his twitter handle is very close to @pwwang: https://twitter.com/pwang

**Comment by pwwang** [comment]
Funny.
