### ISSUE TITLE
Should we encourage or discourage copy/pasting code from the text into the editor/shell?

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#35]
The text has a lot of steps that say "run this exact code". The easiest thing for the user to do is then select the code and copy and paste it.

The problem is that students learn and absorb much better if they manually type in the code (citation needed, too lazy right now). So I want to prevent or discourage copy/pasting.

On the other hand, students will get annoyed if they have to type in lots of code. Sometimes the code they have to run is quite long, and if they don't get it exactly right (except some small differences like spacing or quotes which are OK - the AST has to match) they won't proceed.

Possible courses of action:

1. Prevent copying from the text entirely. Or conversely, prevent pasting into the editor/shell.
2. Prevent copying certain snippets of code, particularly small ones.
3. Allow all copying, but the first time a student does it, show a pop up suggesting that this is bad for learning and they should try to avoid it.
4. Accept that students don't want to type code, and make it easier to run code without typing. This could be combined with either 2 (in cases that copying is allowed) or 3. We could provide a button that copies the code to the clipboard, or even a button that immediately runs the code in the shell/editor.

I prefer either 2 or 3. Thoughts? Ideas?

**Comment by spamegg1** [comment]
This is a tricky balance... We don't want to annoy the user. 

I would be in favor of something in between 2 and 3: tell the student to "Type" explicitly in text, maybe disallow copying small snippets, allow copying medium snippets, but have a "Copy" button for very large snippets and discourage typing those. 

That is what I did in my project. Only the really large snippets have a "Copy" button, and only when the code in the large snippet has already been discussed earlier in smaller chunks, and the large snippet is given as a check to make sure the user did not make a mistake: "this is what your code should look like so far" type of thing.

If this is too complicated, I'm in favor of 2.

**Comment by aninuth** [comment]
As a computer science student, one thing that I've seen professors do often is to not actually provide fully written out code.  They'll make pseudocode available and be very specific about the structure and intended function of the code, but the task of translating those ideas into the language that we're working in must be completed by the student.  This might be a little too advanced for beginners (especially if the goal is to teach syntax and not focusing on problem-solving), but I've found it to be rather helpful.

**Comment by alexmojaki** [comment]
@aninuth I do agree it's better to avoid giving the exact code to write and I try to avoid it where possible, but very often it's necessary. As you say, the goal is often to teach syntax. Besides that we always need a way to check that the user has typed in the correct code, and doing so is a lot more complicated when the student is allowed to be flexible.

So the question in the end is how to handle copy pasting in the many cases when the exact code is simply presented to the user.

**Comment by eddieantonio** [comment]
> This is a tricky balance... We don't want to annoy the user.
> 
> I would be in favor of something in between 2 and 3: tell the student to "Type" explicitly in text, maybe disallow copying small snippets, allow copying medium snippets, but have a "Copy" button for very large snippets and discourage typing those.
> 
> That is what I did in my project. Only the really large snippets have a "Copy" button, and only when the code in the large snippet has already been discussed earlier in smaller chunks (no point in retyping it), and the large snippet is given as a check to make sure the user did not make a mistake: "this is what your code should look like so far" type of thing.

I second this opinion. Copy-pasting should be STRONGLY discouraged, although, some of the course material is written such that it wants you to just try a big chunk of code. It would be SUPER annoying and frustrating if you can't copy-paste that huge chunk. To support both use cases, here is my suggestion: examples that can be copy-pasted should have a big ol' <kbd>Copy</kbd> button. When smaller snippets are copy-pasted, the editor should politely discourage it every single time.

Explict instruction is important too:  "Type this snippet into the editor" vs. "Copy this code into the editor"

**Comment by alexmojaki** [comment]
I've also come to a similar conclusion: adding a helpful copy button (as opposed to just allowing normal copying) for certain snippets (especially large ones) could actually subtly encourage not copying when the button isn't there. It's like saying "we get it, typing sucks, we've made copying convenient when it's appropriate, but this is not one of those times".

OK, so two questions:

1. What level of convenience do we provide for big snippets?
    a. Copy to the clipboard - user still has to paste and run.
    b. Copy and paste straight into the editor - user still has to run.
    c. Copy into the editor and run immediately. I feel like if we're going to provide some convenience, it might as well be this.
2. How do we discourage other copying? I think it has to be something that happens when copying rather than when pasting, so that we can detect if they copied something they shouldn't have.
    a. Show some kind of modal dialog that the user has to explicitly dismiss by clicking OK or X. Do we add a "do not show this again" checkbox?
    b. Same as above but not modal, i.e. a message on the side that isn't in the way but doesn't go away without dismissal.
    c. Something that automatically disappears after a few seconds, like a toast. This could be a whole message or as small as :angry: or :clipboard: :cry: . We could start with option (a) and if the user checks "do not show this again" we downgrade to this version.

**Comment by eddieantonio** [comment]
>    c. Copy into the editor and run immediately. I feel like if we're going to provide some convenience, it might as well be this.

Like a <kbd>Try it!</kbd> button! I like this idea!

> 2. How do we discourage other copying? I think it has to be something that happens when copying rather than when pasting, so that we can detect if they copied something they shouldn't have.
>    a. Show some kind of modal dialog that the user has to explicitly dismiss by clicking OK or X. Do we add a "do not show this again" checkbox?
>    b. Same as above but not modal, i.e. a message on the side that isn't in the way but doesn't go away without dismissal.
>    c. Something that automatically disappears after a few seconds, like a toast. This could be a whole message or as small as 😠 or 📋 😢 . We could start with option (a) and if the user checks "do not show this again" we downgrade to this version.

Haha, I think I like option b best.

**Comment by alexmojaki** [comment]
OK, this is implemented in #68.

1. I went with option b because sometimes users should copy without actually running, or run with a particular debugger.
2. The users get a message like the kind that shows when they make specific mistakes while solving an exercise. In particular this means that the message will only show once for a particular page load, even if you copy many times. Refreshing the page resets this so that the message may appear again.

Try it out here, confirm that it works for you, and let me know what you think: https://pipeline-copying-7ofmbap7hkayr.herokuapp.com/course/?page=CombiningCompoundStatements

**Comment by alexmojaki** [comment]
Also just added https://github.com/alexmojaki/futurecoder/commit/fde1384d2617cde6ac7ae7d1b8caf8cb59e83ca2 to completely prevent copying the hints or solution. That's deployed now.
