### ISSUE TITLE
Specifying Python-specific information

### ISSUE THREAD

**Issue by aninuth** [alexmojaki/futurecoder#37]
Would it be worthwhile to mention that certain things (particularly types) are Python-specific? It could make the instructions more complicated, but it could reduce confusion in case users plan on using the same high-level concepts in other languages.  

This isn't really for low-level stuff and wouldn't have anything to do with the compiler or the machine arch side of things, but instead for things like the following:

> The values are often referred to as elements. They can be anything: numbers, strings, booleans, even lists! They can also be a mixture of types.

This could be rewritten as: 

> The values are often referred to as elements. They can be anything: numbers, strings, booleans, even lists! In Python, they can also be a mixture of types.

**Comment by alexmojaki** [comment]
I don't think so. Other languages are different in all sorts of ways, this will become obvious when beginners learn their second language. I think it will add a lot of clutter with little value, and we'd probably only cover a fraction of the differences.

I'll leave this issue open for a little in case anyone else wants to add an opinion.

**Comment by alexmojaki** [comment]
btw thanks for reporting #30.
