### ISSUE TITLE
Relax the dependecy over python3.10.2

### ISSUE THREAD

**Issue by vincentxavier** [alexmojaki/futurecoder#395]
`pyproject.toml` imposes a hard dependency on a specific Python version. Maybe we could lower it.

**Comment by alexmojaki** [comment]
Unfortunately not, it's to match the Python version used in Pyodide, which is what the Python code actually runs in. Packaging dependencies and running tests shouldn't happen in a different version.

**Comment by vincentxavier** [comment]
Just have a look at https://forge.aeif.fr/futurecoder/futurecoder.forge.aeif.fr/-/compare/main...pyproject and https://fr.futurecoder.io/course/#IntroducingDictionaries
