### ISSUE TITLE
for statements not showing up blue 

### ISSUE THREAD

**Issue by sream90** [alexmojaki/futurecoder#430]
I just started and keep getting stuck with the editor and "for" statements. I copy the exercise exactly as shown, but my "for" shows up red instead of light blue. The system will not let me advance to the next page and is not marking the task as completed correctly.

**Comment by alexmojaki** [comment]
The difference in colour is normal, unfortunately there's just two different syntax highlighters that aren't easy to reconcile.

> The system will not let me advance to the next page and is not marking the task as completed correctly.

You'll have to give more detail, maybe a screenshot.

**Comment by sream90** [comment]
![Image 4-26-23 at 3 05 PM](https://user-images.githubusercontent.com/131911668/234690213-becb0fdc-47b2-4389-861e-103101845f65.jpg)

**Comment by sream90** [comment]
The example shows the word "for" in blue. No matter how I put in "for", it will only show up red.

**Comment by alexmojaki** [comment]
Yes, as I said that's normal, nothing to worry about and not easy to change. I can only help with your trouble with the exercise. I was expecting the screenshot to show the output of your code, the exercise you were on, etc.

**Comment by sream90** [comment]
Ok. Thank you.
