### ISSUE TITLE
micropip in pyodide

### ISSUE THREAD

**Issue by rootsmusic** [alexmojaki/futurecoder#442]
I tried pasting the [code block for micropip](https://github.com/pyodide/pyodide/issues/2500#issuecomment-1118137572), but the second line's call to [micropip](https://github.com/pyodide/pyodide/tree/main/packages/micropip) gave a SyntaxError.  Is this a bug with pyodide?  Thanks.

**Comment by alexmojaki** [comment]
This is JS, not Python:

```js
await pyodide.loadPackage("micropip");
const micropip = pyodide.pyimport("micropip");
await micropip.install("seaborn");
```

In particular the `const` isn't valid Python. But futurecoder doesn't support top-level `await`.

`import seaborn` works fine in futurecoder and automatically installs it with micropip, so you don't need to do anything.

But futurecoder has no visual output section for you to see plots.

Try https://papyros.dodona.be/?locale=en&language=Python
