### ISSUE TITLE
if et else, le bloc sinon 

### ISSUE THREAD

**Issue by louloudev59** [alexmojaki/futurecoder#448]
![image](https://github.com/alexmojaki/futurecoder/assets/106763258/ec04fe6b-e538-4356-98f2-0b572d9c6b24)
Je ne comprend pas pourquoi il ne reconnait pas else

**Comment by alexmojaki** [comment]
```python
if ravi:
    caractere = '!'
    phrase += caractere  # indente
else:
    caractere = '.'
    phrase += caractere  # indente
