### ISSUE TITLE
Would like ability to start 100% new, with no solutions shown

### ISSUE THREAD

**Issue by JinxLuckless** [alexmojaki/futurecoder#475]
I did a lot of exercises over a two-day period, but then I caught the flu, and it's been 3 weeks since I was able to work on it. I remember nothing. I used the table of contents to go back to the beginning. However, sometimes it's showing me the solution because I'd already done it once, and this is not ideal for me.

For instance, this page:
https://futurecoder.io/course/#AddingStrings

It asks me to combine Hello and World with a space, but then immediately says, "Well done! Any of the following are valid solutions:" and shows me all the answers. I would like an option to wipe my progress or otherwise have it not know that I've completed it before.

Thanks!

**Comment by alexmojaki** [comment]
You can either sign out and create a new account, or use Settings -> Developer Mode.

**Comment by JinxLuckless** [comment]
Okay great, thank you! Will have to try that.
