### ISSUE TITLE
Output predictions in List Functions pages

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#78]
Now that #73 is merged, I think we should use it in the new and improved pages about functions/methods for lists. For example, we currently have this:

Here's some new things. Try them out in the shell. Again suppose we have a list `nums = [1, 2, 3]`.

- **`subscript assignment`**: Set a value at an index. `nums[0] = 9` changes the list to `[9, 2, 3]`.

----

This should be changed to something like:

Here's some new things.

- **`subscript assignment`**: Set a value at an index using the syntax `some_list[index] = new_value`. For example, run this program:

```python
nums = [1, 2, 3]
nums[0] = 9
print(nums)
```

----

Then they have to pass a verbatim step with an appropriate `predicted_output_choices`. This is documented now under https://github.com/alexmojaki/futurecoder/blob/master/how_to_contribute.md#steps, it's pretty straightforward.

@spamegg1 I think it makes sense for you to do this, are you keen?

**Comment by spamegg1** [comment]
@alexmojaki Sure thing. It will take me a few days to start on it, still busy with some family stuff. I'll tell you when I can be an assignee.

**Comment by spamegg1** [comment]
OK sign me up. Should I go straight to PR?

**Comment by alexmojaki** [comment]
Let's start with a markdown draft

**Comment by spamegg1** [comment]
OK. Should I start from the `Functions and Methods for Lists` page? Anything needed for the pages before that?

**Comment by alexmojaki** [comment]
Yes, this is just for the 8 or so *new* functions/concepts on those two pages

**Comment by spamegg1** [comment]
I was thinking of having `Error` as some of the multiple choices. 

Should I explain some of the error causes that are not currently explained? For example, with subscript assignment, if `index` is out of range then `some_list[index]` will give an error.

This can be useful to check their understanding. For example, in
 
```python
nums = [1, 2, 3]
nums[0] = 9
print(nums)
```
they might think that the value `0` should be updated to `9`, or they might forget that the index starts at `0` and expect it to start at `1`, so they might think it's out of range.

Or is this just overkill? Is it OK to add `Error` to the choices without explaining the cause of it?

**Comment by alexmojaki** [comment]
Error is always automatically the last choice in all questions. This makes it less obvious when Error actually is the answer.

Let's make it `nums[1] = 9` and then one of the options can be `[9, 2, 3]` to catch them if they're not paying attention.

Adding a second question `nums[3] = 9` might be interesting but I'm not sure if it's needed. I think in that case it's best to mention in the initial explanation what happens if the index is out of range.

**Comment by spamegg1** [comment]
OK, I'll mention the index out of range issue.

**Comment by spamegg1** [comment]
### ...on the Functions and Methods for Lists page

#### Step

Here's some new things. 

- **`subscript assignment`**: Set a value at an index using the syntax `some_list[index] = new_value`. Raises an error if `index` is not a valid index of `some_list`. For example, run this program:

```python
nums = [1, 2, 3]
nums[1] = 9
print(nums)
```

**What do you think the result will be?**

- `[1, 9, 2, 3]`
- `[9, 2, 3]`
- `[1, 9, 3]`
- `Error`

*Correct answer: [1, 9, 3]*

#### Step

- **`index`**: Returns the first index of a value in a list using the syntax `some_list.index(value)`. Raises an error if the value isn't there. For example, run this program:

```python
print([7, 8, 9, 8].index(8))
```

**What do you think the result will be?**

- `[7, 8]`
- `1`
- `[7, 8, 9, 8]`
- `3`
- `Error`

*Correct answer: 1*

#### Step

- **`pop`**: Removes and returns an element at a given index using the syntax `some_list.pop(index)`. Without an argument, i.e. just `some_list.pop()`, it will remove and return the last element. For example, run this program:

```python
nums = [1, 2, 3]
nums.pop(1)
print(nums)
```

**What do you think the result will be?**

- `[2, 3]`
- `2`
- `[1, 3]`
- `1`
- `Error`

*Correct answer: [1, 3]*

#### Step

- **`remove`**: Removes the first occurrence of the given value using the syntax  `some_list.remove(value)`. Raises an error if the value doesn't exist. For example run this program:

```python
nums = [1, 2, 3]
nums.remove(3)
print(nums)
```

**What do you think the result will be?**

- `[1, 2]`
- `[1, 3]`
- `3`
- `Error`

*Correct answer: [1, 2]*

*...page continues...*

## ...on the More List Functions and Methods page

#### Step

Here are a few more useful functions/methods.

- `sorted`: Takes an iterable and returns a list of the elements in order, using the syntax `sorted(some_list)`. 

```python
nums = [28, 99, 10, 81, 59, 64]
new_nums = sorted(nums)
print(new_nums)
```

**What do you think the result will be?**

- `[99, 81, 64, 59, 28, 10]`
- `[10, 81, 64, 28, 59, 99]`
- `[28, 99, 10, 81, 59, 64]`
- `[10, 28, 59, 64, 81, 99]`
- `Error`

*Correct answer: [10, 28, 59, 64, 81, 99]*

#### Step

- `in`: A comparison operator that checks if a value is in a list. For example run this program:

```python
nums = [28, 99, 10, 81, 59, 64]
print(54 in nums)
print(28 in nums)
```

**What do you think the result will be?**

- `True`

  `False`

- `False`

  `True`

- `True`

  `True`

- `Error`

*Correct answer: False, True*

#### Step

- `sum`: Add a list of numbers.

```python
nums = [3, -2, -4, 8, 5, -6]
total = sum(nums)
print(total)
```

**What do you think the result will be?**

- `10`
- `4`
- `-6`
- `Error`

*Correct answer: 4*

#### Step

- count: Returns the number of times the argument appears in the list. 

```python
print([1, 2, 3, 2, 7, 2, 5].count(2))
```

**What do you think the result will be?**

- `0`
- `1`
- `2`
- `3`
- `Error`

*Correct answer: 3*

*...page continues...*

**Comment by alexmojaki** [comment]
Great work at top speed! The overall structure is exactly what we need, I only want to make some minor tweaks:

- Single expressions like index and sorted should be done in the shell
- Also print `nums.pop(1)`
- Write "from smallest to largest" in the sorted step.
- Sum a small easy list of numbers, remember those who hate maths.

You can go straight to a PR.

**Comment by spamegg1** [comment]
OK. Shell works the same as editor in VerbatimStep, right? It's just `program = "..."`

**Comment by alexmojaki** [comment]
Yes, just leave out print and set `expected_code_source = "shell"`.

**Comment by spamegg1** [comment]
`docker-compose build` is failing on Step 16

```
Step 16/31 : RUN DEBIAN_FRONTEND=noninteractive apt-get install -y     python3.8-dev     vim     python3.8-distutils     gcc     postgresql-client-12     git     libpq-dev
```
Gives a bunch of 404 Not Found errors trying to download Ubuntu 18.04 packages (I'm on 20.04 but I guess that doesn't matter because it's a container?)

```
...
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/v/vim/vim_8.0.1453-1ubuntu1.3_amd64.deb  404  Not Found [IP: 91.189.88.142 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 105 MB in 1min 28s (1198 kB/s)
ERROR: Service 'web' failed to build: The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y     python3.8-dev     vim     python3.8-distutils     gcc     postgresql-client-12     git     libpq-dev' returned a non-zero code: 100
```

**Comment by alexmojaki** [comment]
Disable the cache so that it builds from scratch, then it will `RUN apt-get update` at the beginning.

**Comment by spamegg1** [comment]
OK, `docker-compose build --no-cache` seems to be working. I learn something every day

**Comment by alexmojaki** [comment]
I've also gotten confused by this in the past, probably more than once. I think this is the first time I figured out the fix immediately.

**Comment by spamegg1** [comment]
OK it's working. Making the PR
