### ISSUE TITLE
Package into offline installable desktop app, e.g. with pyinstaller

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#89]
**EDIT: now that production is using pyodide, this is a lower priority. Plus, the code is going through a major transformation, and Django is probably going to be removed. So this isn't a great time for this.**

-----

We need a futurecoder 'app' that is entirely self contained and runs locally. The advantages for the user are:

- Doesn't require internet access once installed
- Works faster since it doesn't need to wait for communication with a server
- The web version restricts CPU time and filesystem access to prevent abuse and security issues. A local version doesn't need these restrictions, which means:
    - No limits on CPU
    - Can do lessons and exercises involving files
    - Can install external packages
    - System is more stable in general, no more processes intermittently dying

The big advantage for us is reduced load on servers.

I've never done this before so I don't know the best way to do it. The important requirements are:

- Must be easy to install for non-technical users.
    - Standard click to download on website and then click a few buttons in a GUI installer.
    - No terminal commands.
    - No previous installation of Python required.
- Prefer cross-platform technologies and solutions. The less work that has to be done to support a specific OS, the better.

EDIT: Initially we looked into using Electron before we realised this is not important. As a first step, let's just make a program which runs the server and opens a browser tab for `localhost:3000` or something. Electron just makes things look a bit fancier.

**Comment by spamegg1** [comment]
I would LOVE to do this... but currently I don't know how to. I'm a lifelong desktop user, love desktop programs and hate doing things in a browser.

I will definitely look into using Electron to accomplish this, but it can take me 6 months-1 year to get anything decent going. [Here](https://www.cloudsavvyit.com/1585/electron-can-bring-your-web-app-to-the-desktop-heres-how-to-get-started/) is a simple article to get started. According to this Electron makes it cross-platform automatically.

**Comment by alexmojaki** [comment]
@spamegg1 could you give this a try? We're heading for a launch and it would be amazing if we had this. That may not be realistic but we actually don't know how hard this would be and if it turns out to be easy it'd be silly not to have it ASAP. I want us to give it a go and investigate.

I glanced at the article you linked, it mentioned starting from a template, not sure if that will be helpful for our existing project.

**Comment by spamegg1** [comment]
I'll investigate some more and give it a shot, but it's probably going to be difficult compared to other apps out there.

To get a rough idea of the difficulty you might want to look at the code of [Gitter](https://gitlab.com/gitterHQ/desktop) which I believe uses Electron to turn their chat web app to a desktop app. They had some [issues open](https://gitlab.com/gitterHQ/desktop/-/issues/290) where they were complaining about the difficulty of maintaining a desktop app, and wanted to phase it out and abandon it.

One other point is the huge overkill of "importing an entire browser" just to run a desktop app, but I guess we don't really have to care about that. Making it from scratch would be a dream but way too difficult.

**Comment by spamegg1** [comment]
Promising lead: https://github.com/fyears/electron-python-example
Uses `zerorpc` to communicate between Electron frontend and Python backend.
The README can give you a good idea of the difficulty.
I'll try to follow along, see what happens. It's outdated and unmaintained though.

**Comment by alexmojaki** [comment]
If you search for "django electron" there's tons of results.
